# Site settings
title: Ultrasonic Anemometer

description: Test description
baseurl: /ultrasonic_anemometer # the subpath of your site, e.g. /blog/

author:
  name : Stuart Feichtinger
  email: stuart.feichtinger@gmail.com
  github : stuthedew


# Build settings
markdown: kramdown
